(()=>{
function fmt(sec){sec=Number(sec);if(!Number.isFinite(sec))return'';const m=Math.floor(sec/60),r=sec-m*60;return `${m}:${r.toFixed(2).padStart(5,'0')}`}
function parseCsv(text){const lines=String(text||'').replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());if(lines.length<2)throw Error('No LapTrophy laps found');const sep=lines[0].includes(';')?';':',';const h=lines[0].split(sep).map(x=>x.trim().toLowerCase()),col=n=>h.indexOf(n);const si=col('session date'),li=col('lap index'),ti=col('time (s)'),mi=col('max. speed (mph)');if(si<0||li<0||ti<0)throw Error('Choose the LapTrophy summary CSV, not the raw GPS log.');const groups=new Map();for(const line of lines.slice(1)){const a=line.split(sep),key=(a[si]||'').trim(),sec=Number(a[ti]);if(!key||!Number.isFinite(sec))continue;if(!groups.has(key))groups.set(key,[]);groups.get(key).push({index:Number(a[li])||groups.get(key).length+1,seconds:sec,maxSpeed:mi>=0?Number(a[mi]):null})}return [...groups].map(([sessionDate,laps])=>({sessionDate,laps:laps.sort((a,b)=>a.index-b.index)})).sort((a,b)=>a.sessionDate.localeCompare(b.sessionDate))}
window.openLapTrophyImport=function(did){modalTitle.textContent='Import LapTrophy';modalBody.innerHTML=`<p class="muted">Export the summary CSV from LapTrophy and choose it here. Timing is matched to Session 1, 2, 3… while your pressures, passenger and notes stay intact.</p><input id="ltfile" type="file" accept=".csv,text/csv,text/plain" style="display:none"><button id="ltchoose" class="btn" style="width:100%;margin-top:12px">Choose LapTrophy CSV</button><p class="small muted">You can import the full day again later. Existing timing is updated, not duplicated.</p>`;ltchoose.onclick=()=>ltfile.click();ltfile.onchange=()=>importLapTrophyFile(did,ltfile.files[0]);modal.showModal()}
window.importLapTrophyFile=function(did,file){if(!file)return;const r=new FileReader();r.onload=()=>{try{const groups=parseCsv(r.result),d=db.days.find(x=>x.id===did);if(!d)throw Error('Track day not found');const fileDate=groups[0]?.sessionDate?.slice(0,10);if(fileDate&&d.date&&fileDate!==d.date&&!confirm(`CSV date ${fileDate} does not match this track day (${d.date}). Import anyway?`))return;groups.forEach((g,i)=>{const best=Math.min(...g.laps.map(x=>x.seconds)),max=Math.max(...g.laps.map(x=>Number.isFinite(x.maxSpeed)?x.maxSpeed:0));let s=d.sessions[i];if(!s){s={id:id(),number:i+1,time:g.sessionDate,lap:'',lapSeconds:null,fuel:'',fuelNote:'',fl:'',fr:'',rl:'',rr:'',brakes:'',temp:'',carNotes:'',driverNotes:'',adjustmentType:'',adjustment:'',passenger:'No'};d.sessions.push(s)}s.number=i+1;s.imported=true;s.importSource='LapTrophy';s.importSessionDate=g.sessionDate;s.lap=fmt(best);s.lapSeconds=best;s.lapCount=g.laps.length;s.maxSpeed=max?max.toFixed(1):'';s.laps=g.laps.map(x=>({index:x.index,seconds:x.seconds,lap:fmt(x.seconds),maxSpeed:Number.isFinite(x.maxSpeed)?x.maxSpeed:null}));if(!s.passenger)s.passenger='No'});modal.close();save();toast(`${groups.length} LapTrophy sessions imported`)}catch(e){alert(e.message||'Could not read that LapTrophy CSV.')}};r.readAsText(file)}
const oldHome=renderHome;renderHome=function(){oldHome();const d=currentDay();if(!d||document.getElementById('ltImportBtn'))return;const sessions=document.querySelector('#home .sectiontitle');if(!sessions)return;const b=document.createElement('button');b.id='ltImportBtn';b.className='btn secondary';b.style='width:100%;margin:10px 0';b.textContent='Import LapTrophy CSV';b.onclick=()=>openLapTrophyImport(d.id);sessions.before(b)};
const oldOpen=openSession;openSession=function(did){oldOpen(did);if(document.getElementById('spassenger'))return;const brakes=document.getElementById('sbr')?.closest('div');if(!brakes)return;const box=document.createElement('div');box.innerHTML='<label>Passenger</label><select id="spassenger"><option>No</option><option>Yes</option></select>';brakes.parentElement.insertBefore(box,brakes)};
const oldSave=saveSession;saveSession=function(did){const passenger=document.getElementById('spassenger')?.value||'No',d=db.days.find(x=>x.id===did),before=d?.sessions?.length||0;oldSave(did);if(d&&d.sessions.length>before){d.sessions[d.sessions.length-1].passenger=passenger;save()}};
const oldCards=sessionCards;sessionCards=function(d){let html=oldCards(d);(d.sessions||[]).forEach(s=>{const needle=`Brakes: ${esc(s.brakes)}`;const prefix=`${s.imported?`LapTrophy · ${s.lapCount||'—'} laps${s.maxSpeed?` · Max ${esc(s.maxSpeed)} mph`:''} · `:''}Passenger: ${esc(s.passenger||'No')} · Brakes: ${esc(s.brakes)}`;html=html.replace(needle,prefix)});return html};
(d=>{(db.days||[]).forEach(x=>(x.sessions||[]).forEach(s=>{if(!s.passenger)s.passenger='No'}));render()})(db);
})();
