const CACHE='track-day-log-v11';
const ASSETS=['./','./index.html','./manifest.webmanifest','./icon.svg','./v6-patch.js','./v7-patch.js','./v8-reset.js','./v10-analysis.js','./v11-history-analysis.js'];
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS)).then(()=>self.skipWaiting()))});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim()))});
self.addEventListener('fetch',event=>{
 if(event.request.method!=='GET')return;
 const req=event.request,nav=req.mode==='navigate'||(req.headers.get('accept')||'').includes('text/html');
 if(nav){event.respondWith((async()=>{try{const res=await fetch(req,{cache:'no-store'}),html=await res.text();let patched=html;const scripts='<script src="./v8-reset.js?v=11"></script><script src="./v6-patch.js?v=11"></script><script src="./v7-patch.js?v=11"></script><script src="./v10-analysis.js?v=11"></script><script src="./v11-history-analysis.js?v=11"></script>';patched=patched.replace(/<script src="\.\/v8-reset\.js[^>]*><\/script>/g,'').replace(/<script src="\.\/v6-patch\.js[^>]*><\/script>/g,'').replace(/<script src="\.\/v7-patch\.js[^>]*><\/script>/g,'').replace(/<script src="\.\/v10-analysis\.js[^>]*><\/script>/g,'').replace(/<script src="\.\/v11-history-analysis\.js[^>]*><\/script>/g,'').replace('</body>',scripts+'</body>');return new Response(patched,{status:res.status,statusText:res.statusText,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'}})}catch(e){const cached=await caches.match('./index.html');if(!cached)return new Response('Offline',{status:503});let html=await cached.text();const scripts='<script src="./v8-reset.js?v=11"></script><script src="./v6-patch.js?v=11"></script><script src="./v7-patch.js?v=11"></script><script src="./v10-analysis.js?v=11"></script><script src="./v11-history-analysis.js?v=11"></script>';html=html.replace(/<script src="\.\/v8-reset\.js[^>]*><\/script>/g,'').replace(/<script src="\.\/v6-patch\.js[^>]*><\/script>/g,'').replace(/<script src="\.\/v7-patch\.js[^>]*><\/script>/g,'').replace(/<script src="\.\/v10-analysis\.js[^>]*><\/script>/g,'').replace(/<script src="\.\/v11-history-analysis\.js[^>]*><\/script>/g,'').replace('</body>',scripts+'</body>');return new Response(html,{headers:{'Content-Type':'text/html; charset=utf-8'}})}})());return}
 event.respondWith(caches.match(req).then(cached=>cached||fetch(req).then(res=>{if(res&&res.ok){const copy=res.clone();caches.open(CACHE).then(c=>c.put(req,copy))}return res})));
});