/* Track Day Log V6: lightweight LapTrophy import + passenger context */
(()=>{
const oldHome=renderHome,oldSettings=renderSettings,oldOpenSession=openSession,oldSaveSession=saveSession;
window.formatLapSeconds=function(sec){sec=Number(sec);if(!Number.isFinite(sec))return'';const m=Math.floor(sec/60),s=sec-m*60;return `${m}:${s.toFixed(2).padStart(5,'0')}`};
window.fixLapDisplay=function(v){if(!v)return v;const p=String(v).split(':');if(p.length!==2)return v;return `${p[0]}:${p[1].padStart(5,'0')}`};
window.parseLapTrophyCsv=function(text){const lines=String(text||'').replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());if(lines.length<2)throw new Error('No LapTrophy laps found');const sep=lines[0].includes(';')?';':',';const h=lines[0].split(sep).map(x=>x.trim().toLowerCase()),col=n=>h.indexOf(n),si=col('session date'),li=col('lap index'),ti=col('time (s)'),mi=col('max. speed (mph)');if(si<0||li<0||ti<0)throw new Error('Choose the LapTrophy summary CSV, not the raw GPS log');const groups=new Map();for(const line of lines.slice(1)){const a=line.split(sep),key=(a[si]||'').trim(),sec=Number(a[ti]);if(!key||!Number.isFinite(sec))continue;if(!groups.has(key))groups.set(key,[]);groups.get(key).push({index:Number(a[li])||groups.get(key).length+1,seconds:sec,maxSpeed:mi>=0?Number(a[mi]):null})}return [...groups.entries()].map(([sessionDate,laps])=>({sessionDate,laps:laps.sort((a,b)=>a.index-b.index)})).sort((a,b)=>a.sessionDate.localeCompare(b.sessionDate))};
window.openLapTrophyImport=function(did){modalTitle.textContent='Import LapTrophy';modalBody.innerHTML=`<p class="muted">Export the summary CSV from LapTrophy, then choose it here. Timing is added to this track day without replacing pressures, passenger or notes.</p><input id="lapTrophyFile" type="file" accept=".csv,text/csv,text/plain" style="display:none"><button id="chooseLapTrophy" class="btn" style="width:100%;margin-top:14px">Choose LapTrophy CSV</button><p class="small muted" style="margin-top:10px">You can import the full-day CSV again later; matching session timing is updated rather than duplicated.</p>`;const input=document.getElementById('lapTrophyFile');document.getElementById('chooseLapTrophy').onclick=()=>input.click();input.onchange=()=>importLapTrophyFile(did,input.files[0]);modal.showModal()};
window.importLapTrophyFile=function(did,file){if(!file)return;const r=new FileReader();r.onload=()=>{try{const groups=parseLapTrophyCsv(r.result),d=db.days.find(x=>x.id===did);if(!d)throw new Error('Track day not found');if(!groups.length)throw new Error('No timed sessions found');const fileDate=groups[0].sessionDate.slice(0,10);if(fileDate&&d.date&&fileDate!==d.date&&!confirm(`This CSV is dated ${fileDate}, but this track day is ${d.date}. Import it anyway?`))return;groups.forEach((g,i)=>{const best=Math.min(...g.laps.map(x=>x.seconds)),max=Math.max(...g.laps.map(x=>Number.isFinite(x.maxSpeed)?x.maxSpeed:0));let ss=d.sessions[i];if(!ss){ss={id:id(),number:i+1,time:g.sessionDate,lap:'',lapSeconds:null,fuel:'',fuelNote:'',fl:'',fr:'',rl:'',rr:'',passenger:'No',brakes:'',temp:'',carNotes:'',driverNotes:'',adjustmentType:'',adjustment:''};d.sessions.push(ss)}ss.number=i+1;ss.imported=true;ss.importSource='LapTrophy';ss.importSessionDate=g.sessionDate;ss.lap=formatLapSeconds(best);ss.lapSeconds=best;ss.lapCount=g.laps.length;ss.maxSpeed=max?max.toFixed(1):''});modal.close();save();toast(`${groups.length} LapTrophy sessions imported`)}catch(e){alert(e.message||'Could not read that LapTrophy CSV')}};r.readAsText(file)};
renderHome=function(){oldHome();const d=currentDay();if(!d)return;(d.sessions||[]).forEach(s=>{if(s.lapSeconds!=null)s.lap=formatLapSeconds(s.lapSeconds);else if(s.lap)s.lap=fixLapDisplay(s.lap)});const host=home.querySelector('.grid');if(host&&!document.getElementById('lapTrophyImportBtn')){const b=document.createElement('button');b.id='lapTrophyImportBtn';b.className='btn secondary';b.style.cssText='width:100%;margin-top:10px';b.textContent='Import LapTrophy CSV';b.onclick=()=>openLapTrophyImport(d.id);host.insertAdjacentElement('afterend',b)}};
openSession=function(did){oldOpenSession(did);const brakes=document.getElementById('sbr');if(brakes&&!document.getElementById('spassenger')){const wrap=brakes.closest('.formgrid')||brakes.parentElement;const box=document.createElement('div');box.innerHTML='<label>Passenger</label><select id="spassenger"><option>No</option><option>Yes</option></select>';wrap.insertBefore(box,wrap.firstChild)}};
saveSession=function(did){const passenger=document.getElementById('spassenger')?.value||'No',d=db.days.find(x=>x.id===did),before=d?.sessions?.length||0;oldSaveSession(did);if(d&&d.sessions.length>before){d.sessions[d.sessions.length-1].passenger=passenger;save()}};
window.clearTrackDays=function(){if(!db.days.length)return toast('No track days to clear');if(!confirm('Clear all track days and sessions? Your garage and recovery code will stay untouched.'))return;db.days=[];save();toast('Track days cleared')};
renderSettings=function(){oldSettings();if(document.getElementById('clearTrackDaysBtn'))return;const cards=settings.querySelectorAll('.card'),anchor=cards[1]||cards[0];if(anchor){const c=document.createElement('div');c.className='card';c.innerHTML='<h3>Test data</h3><p class="small muted">Clear track days and sessions without touching your garage or recovery setup.</p><button id="clearTrackDaysBtn" class="btn danger" style="width:100%" onclick="clearTrackDays()">Clear all track days</button>';anchor.insertAdjacentElement('afterend',c)}};
render();
})();